services:
  mysql-db:
    image: mysql:9.1
    restart: always
    container_name: mysql-data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/scripts:/docker-entrypoint-initdb.d
    user:
      mysql
volumes:
  mysql-data:
    driver: local